### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ForestQ** [koolhand/rss-from-webpage#1]
Can you show how to use the script?

**Comment by koolhand** [comment]
Hi ForestQ, it's been a while since I played with this, and it's incomplete. I'm not actually a programmer ;) I was just learning, and didn't dedicate enough time to make it generic enough, or a proper program. Feel free to play with it, but there are probably better examples out there.

I had it working to generate valid Atom or RSS feed, from a source HTML page - but it would just create an .atom file. It wasn't yet hosted in a webserver, to let you use a feedreader like Feedly to subscribe.

I think the container_CSS_selector would find the outer container, and assume all links within it were valid, but on the source site I used as an example, the HTML classes & IDs have changed and I haven't run it for a while, so I can't check that quickly.
